const ORDER_STATUS = {
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  PROCESSING: "PROCESSING",
  READY_FOR_DISPATCH: "READY_FOR_DISPATCH",
  SHIPPED: "SHIPPED",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
  FAILED: "FAILED"
};

const PAYMENT_STATUS = {
  PENDING: "PENDING",
  PAID: "PAID",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED",
  PARTIALLY_REFUNDED: "PARTIALLY_REFUNDED"
};

const BUYER_TYPE = {
  CONSUMER: "CONSUMER",
  BULK_BUYER: "BULK_BUYER"
};

module.exports = {
  ORDER_STATUS,
  PAYMENT_STATUS,
  BUYER_TYPE
};
