const PERMISSIONS = {
  USER_VIEW: "USER_VIEW",
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",

  PRODUCT_VIEW: "PRODUCT_VIEW",
  PRODUCT_CREATE: "PRODUCT_CREATE",
  PRODUCT_UPDATE: "PRODUCT_UPDATE",
  PRODUCT_DELETE: "PRODUCT_DELETE",

  INVENTORY_VIEW: "INVENTORY_VIEW",
  INVENTORY_MANAGE: "INVENTORY_MANAGE",

  ORDER_VIEW: "ORDER_VIEW",
  ORDER_CREATE: "ORDER_CREATE",
  ORDER_UPDATE: "ORDER_UPDATE",
  ORDER_CANCEL: "ORDER_CANCEL",

  BULK_ORDER_VIEW: "BULK_ORDER_VIEW",
  BULK_ORDER_CREATE: "BULK_ORDER_CREATE",
  BULK_ORDER_UPDATE: "BULK_ORDER_UPDATE",
  BULK_ORDER_CANCEL: "BULK_ORDER_CANCEL",
  BULK_ORDER_MANAGE: "BULK_ORDER_MANAGE",

  FPO_MEMBER_VIEW: "FPO_MEMBER_VIEW",
  FPO_MEMBER_MANAGE: "FPO_MEMBER_MANAGE",

  SETTLEMENT_VIEW: "SETTLEMENT_VIEW",
  SETTLEMENT_MANAGE: "SETTLEMENT_MANAGE",

  LOGISTICS_JOB_VIEW: "LOGISTICS_JOB_VIEW",
  LOGISTICS_JOB_ACCEPT: "LOGISTICS_JOB_ACCEPT",
  LOGISTICS_JOB_UPDATE: "LOGISTICS_JOB_UPDATE",

  ROUTE_VIEW: "ROUTE_VIEW",
  ROUTE_OPTIMIZE: "ROUTE_OPTIMIZE",

  SHIPMENT_VIEW: "SHIPMENT_VIEW",
  SHIPMENT_UPDATE: "SHIPMENT_UPDATE",

  PAYMENT_CREATE: "PAYMENT_CREATE",

  REPORT_VIEW: "REPORT_VIEW",
  REPORT_GENERATE: "REPORT_GENERATE",

  AUDIT_VIEW: "AUDIT_VIEW",

  DASHBOARD_VIEW: "DASHBOARD_VIEW"
};

module.exports = PERMISSIONS;
