const PRODUCT_SELLER_TYPE = {
  FARMER: "FARMER",
  FPO: "FPO"
};

const PRODUCT_CATEGORY = {
  VEGETABLE: "VEGETABLE",
  FRUIT: "FRUIT",
  GRAIN: "GRAIN",
  PULSE: "PULSE",
  SPICE: "SPICE",
  OTHER: "OTHER"
};

const PRODUCT_UNIT = {
  KG: "KG",
  QUINTAL: "QUINTAL",
  TON: "TON",
  PIECE: "PIECE"
};

const PRODUCT_QUALITY_GRADE = {
  A: "A",
  B: "B",
  C: "C"
};

const PRODUCT_STATUS = {
  PENDING_APPROVAL: "PENDING_APPROVAL",
  ACTIVE: "ACTIVE",
  REJECTED: "REJECTED",
  INACTIVE: "INACTIVE"
};

const PRODUCT_APPROVAL_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED"
};

module.exports = {
  PRODUCT_SELLER_TYPE,
  PRODUCT_CATEGORY,
  PRODUCT_UNIT,
  PRODUCT_QUALITY_GRADE,
  PRODUCT_STATUS,
  PRODUCT_APPROVAL_STATUS
};