const FARM_LAND_UNIT = Object.freeze({
  ACRE: "ACRE",
  HECTARE: "HECTARE"
});

const FARM_OWNERSHIP_TYPE = Object.freeze({
  OWNED: "OWNED",
  LEASED: "LEASED",
  SHARED: "SHARED"
});

const BUYER_BUSINESS_TYPE = Object.freeze({
  HOTEL: "HOTEL",
  RESTAURANT: "RESTAURANT",
  RETAILER: "RETAILER",
  WHOLESALER: "WHOLESALER",
  PROCESSOR: "PROCESSOR",
  CATERER: "CATERER",
  INSTITUTION: "INSTITUTION",
  OTHER: "OTHER"
});

const FPO_MEMBER_STATUS = Object.freeze({
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  SUSPENDED: "SUSPENDED"
});

const PROFILE_VERIFICATION_STATUS = Object.freeze({
  PENDING: "PENDING",
  VERIFIED: "VERIFIED",
  REJECTED: "REJECTED"
});

const LOGISTICS_PARTNER_TYPE = Object.freeze({
  LOGISTICS_PARTNER: "LOGISTICS_PARTNER"
});

module.exports = {
  FARM_LAND_UNIT,
  FARM_OWNERSHIP_TYPE,
  BUYER_BUSINESS_TYPE,
  FPO_MEMBER_STATUS,
  PROFILE_VERIFICATION_STATUS,
  LOGISTICS_PARTNER_TYPE
};