const APP_NAME = "FarmDirect";

const API_PREFIX = "/api";

const ROLES = {
  ADMIN: "ADMIN",
  FARMER: "FARMER",
  CONSUMER: "CONSUMER",
  BULK_BUYER: "BULK_BUYER",
  FPO: "FPO",
  LOGISTICS: "LOGISTICS",
  GOVERNMENT_OFFICER: "GOVERNMENT_OFFICER"
};

const USER_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  SUSPENDED: "SUSPENDED",
  PENDING: "PENDING"
};

const VERIFICATION_STATUS = {
  PENDING: "PENDING",
  VERIFIED: "VERIFIED",
  REJECTED: "REJECTED"
};

const ORDER_STATUS = {
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  PROCESSING: "PROCESSING",
  READY_FOR_PICKUP: "READY_FOR_PICKUP",
  SHIPPED: "SHIPPED",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED"
};

const PAYMENT_STATUS = {
  PENDING: "PENDING",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED"
};

const PRODUCT_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  OUT_OF_STOCK: "OUT_OF_STOCK"
};

module.exports = {
  APP_NAME,
  API_PREFIX,
  ROLES,
  USER_STATUS,
  VERIFICATION_STATUS,
  ORDER_STATUS,
  PAYMENT_STATUS,
  PRODUCT_STATUS
};
